services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ticket-sales
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: