### Get all events
GET http://localhost:3000/events

### Create an event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "This is a new event",
    "date": "2024-07-08T20:09:32",
    "price": 100
}

### Event ID var
@eventId = {{ createEvent.response.body.id }}

### Get event by ID
GET http://localhost:3000/events/{{eventId}}

### Update an event
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "Updated Event",
    "description": "This is an updated event",
    "date": "2024-07-10T20:09:32"
}

### Delete an event
DELETE http://localhost:3000/events/{{eventId}}


### SPOT
### Get all spots of an event
GET http://localhost:3000/events/{{eventId}}/spots

### Create a spot
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A7"
}

### Event ID var
@spotName = {{ createSpot.response.body.name }}

### Reserve a spot
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
    "spots": ["{{spotName}}"],
    "ticket_kind": "full",
    "email": "test@test.com"
}
